---
pinpress:
  config_location: "/tmp/pp/.pinpress"
  default_pin_template: pinpress_default
  default_tag_template: pinpress_default
  log_level: WARN
  api_token: bachya:12345
pin_templates:
- pinpress_default:
    opener: "<ul>"
    item: <li><%= href %></li>
    closer: "</ul>"
tag_templates:
- pinpress_default:
    item: "<%= tag %> (<%= count %>),"
links: {}
